/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard.templates'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardProductRouteImport } from './routes/dashboard.product'
import { Route as DashboardImageRouteImport } from './routes/dashboard.image'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardFavoritesRouteImport } from './routes/dashboard.favorites'
import { Route as DashboardCaptionRouteImport } from './routes/dashboard.caption'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAdcopyRouteImport } from './routes/dashboard.adcopy'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductRoute = DashboardProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImageRoute = DashboardImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFavoritesRoute = DashboardFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCaptionRoute = DashboardCaptionRouteImport.update({
  id: '/caption',
  path: '/caption',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdcopyRoute = DashboardAdcopyRouteImport.update({
  id: '/adcopy',
  path: '/adcopy',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/dashboard/adcopy': typeof DashboardAdcopyRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/caption': typeof DashboardCaptionRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/image': typeof DashboardImageRoute
  '/dashboard/product': typeof DashboardProductRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/dashboard/adcopy': typeof DashboardAdcopyRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/caption': typeof DashboardCaptionRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/image': typeof DashboardImageRoute
  '/dashboard/product': typeof DashboardProductRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/dashboard/adcopy': typeof DashboardAdcopyRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/caption': typeof DashboardCaptionRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/image': typeof DashboardImageRoute
  '/dashboard/product': typeof DashboardProductRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/api/generate-image'
    | '/dashboard/adcopy'
    | '/dashboard/analytics'
    | '/dashboard/caption'
    | '/dashboard/favorites'
    | '/dashboard/history'
    | '/dashboard/image'
    | '/dashboard/product'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/api/generate-image'
    | '/dashboard/adcopy'
    | '/dashboard/analytics'
    | '/dashboard/caption'
    | '/dashboard/favorites'
    | '/dashboard/history'
    | '/dashboard/image'
    | '/dashboard/product'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/api/generate-image'
    | '/dashboard/adcopy'
    | '/dashboard/analytics'
    | '/dashboard/caption'
    | '/dashboard/favorites'
    | '/dashboard/history'
    | '/dashboard/image'
    | '/dashboard/product'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/product': {
      id: '/dashboard/product'
      path: '/product'
      fullPath: '/dashboard/product'
      preLoaderRoute: typeof DashboardProductRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/image': {
      id: '/dashboard/image'
      path: '/image'
      fullPath: '/dashboard/image'
      preLoaderRoute: typeof DashboardImageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/favorites': {
      id: '/dashboard/favorites'
      path: '/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof DashboardFavoritesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/caption': {
      id: '/dashboard/caption'
      path: '/caption'
      fullPath: '/dashboard/caption'
      preLoaderRoute: typeof DashboardCaptionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/adcopy': {
      id: '/dashboard/adcopy'
      path: '/adcopy'
      fullPath: '/dashboard/adcopy'
      preLoaderRoute: typeof DashboardAdcopyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdcopyRoute: typeof DashboardAdcopyRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCaptionRoute: typeof DashboardCaptionRoute
  DashboardFavoritesRoute: typeof DashboardFavoritesRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardImageRoute: typeof DashboardImageRoute
  DashboardProductRoute: typeof DashboardProductRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdcopyRoute: DashboardAdcopyRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCaptionRoute: DashboardCaptionRoute,
  DashboardFavoritesRoute: DashboardFavoritesRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardImageRoute: DashboardImageRoute,
  DashboardProductRoute: DashboardProductRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
